### ISSUE TITLE
First test build

### ISSUE THREAD

**Issue by crawleyde** [OPLBPO/oplbootstrap_helper#12]
Went ok, after I reset permissions to the www-data group for sites/default/files. I got another notice about file temporary... not being writable, but that seemed to just implicate default/files, since that notice is gone now. 

On prod I think I'll repeat Tuesday's process of changing the cookie name of bc_session in Varnish so apache doesn't receive that traffic. Seemed to help when we did that. Noting to @ClassicCut for info, and @davekisly and @csimmons44 to check any of the changes that were pushed.

**Comment by ClassicCut** [comment]
As I am about to commit the updated make file stucture to opl_make, I'm wondering if the bootstrap-theme-development branch is the one that should be used for the drupal core (opl-d7 repo), or should I switch it to opl-d7 branch?

**Comment by crawleyde** [comment]
I'd leave it as is for now, because the merge back into opl-d7 still has some outstanding issues in https://github.com/OPLBPO/opl-d7/pull/423#issuecomment-262532090. I think it's possibly a ctools conflict? Is it possible to revert that merge at this point?

**Comment by crawleyde** [comment]
We're going to do our first make-file prod update today at 2pm, if you @ClassicCut don't mind setting aside some time to help if needed. I don't expect any issues.

**Comment by ClassicCut** [comment]
No problem. I'll be available.

**Comment by crawleyde** [comment]
So instead of calling opl.make, it looks like I call build-opl-d7.make?

**Comment by ClassicCut** [comment]
Yep, that's correct.

**Comment by ClassicCut** [comment]
I added a README to the opl_make project that explains the structure and commands for building and deploying. I'm working on fleshing it out currently.

**Comment by crawleyde** [comment]
We've done a couple of updates now, and the process is definitely getting easier. I'm still a bit wistful about losing our overall git tag, but will get over it. Perhaps we could keep the previous copy of the 'build' folder and date it in case we wanted to quickly roll back to a previous build. @ClassicCut @minorOffense , do you track release notes somehow that can accompany a build?

**Comment by ClassicCut** [comment]
You can still incorporate the git tag into the deployment workflow. See my notes here on the opl_make project (https://github.com/OPLBPO/opl_make).
In particular, take a look at the drupal-org-core.make file where you can set a tag to be checked out from the specified repo & branch.
This would allow you to continue working with tagged repo states. Also the same practice could be applied to the opl_make project: when major version changes happen (not necessarily for each new core tag but you could do it that way if you wish) and the new versions are put into the make files, create a tag on opl_make that matches the core tag, that way you can keep both in sync, and the builds from the make file can be reproduced for past builds.
